import manifest from "../../public/blurhash-manifest.json";

/**
 * Build-time blurhash + LQIP manifest. Generated by
 * `scripts/generate-blurhashes.mjs` — re-run when images change.
 *
 * Each entry stores:
 *   - hash:    the blurhash string (4×4 components, suitable for the
 *              `blurhash` npm package's `decode()`).
 *   - dataURL: a tiny base64 PNG placeholder (~600 bytes), ready to
 *              pass to next/image as `blurDataURL`.
 *   - width / height: native pixel dimensions for layout reservation.
 */
export type BlurEntry = {
  hash: string;
  dataURL: string;
  width: number;
  height: number;
  mtime?: number;
};

const map = manifest as Record<string, BlurEntry>;

export const getBlur = (src: string | undefined | null): BlurEntry | null => {
  if (!src) return null;
  const key = src.startsWith("/") ? src : `/${src}`;
  return map[key] ?? null;
};
