import type { IndianCityMaster } from "@/types/master";

export const FALLBACK_INDIAN_CITIES: IndianCityMaster[] = [
  {
    _id: "fallback-mumbai",
    value: "Mumbai",
    city: "Mumbai",
    cityId: "mumbai",
    state: "Maharashtra",
    latitude: 19.076,
    longitude: 72.8777,
  },
  {
    _id: "fallback-delhi",
    value: "Delhi NCR",
    city: "Delhi",
    cityId: "delhi-ncr",
    state: "Delhi",
    latitude: 28.6139,
    longitude: 77.209,
  },
  {
    _id: "fallback-bengaluru",
    value: "Bengaluru",
    city: "Bengaluru",
    cityId: "bengaluru",
    state: "Karnataka",
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    _id: "fallback-pune",
    value: "Pune",
    city: "Pune",
    cityId: "pune",
    state: "Maharashtra",
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    _id: "fallback-hyderabad",
    value: "Hyderabad",
    city: "Hyderabad",
    cityId: "hyderabad",
    state: "Telangana",
    latitude: 17.385,
    longitude: 78.4867,
  },
  {
    _id: "fallback-chennai",
    value: "Chennai",
    city: "Chennai",
    cityId: "chennai",
    state: "Tamil Nadu",
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    _id: "fallback-kolkata",
    value: "Kolkata",
    city: "Kolkata",
    cityId: "kolkata",
    state: "West Bengal",
    latitude: 22.5726,
    longitude: 88.3639,
  },
  {
    _id: "fallback-goa",
    value: "Goa",
    city: "Goa",
    cityId: "goa",
    state: "Goa",
    latitude: 15.2993,
    longitude: 74.124,
  },
];
